language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get install qt5-default libqt5xmlpatterns5-dev -y
script:
  - python setup.py install # --qmake=/path/to/bin/qmake --cmake=/path/to/bin/cmake --openssl=/path/to/openssl/bin
