install:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: python --version
  - cmd: python setup.py install --qmake=\path\to\bin\qmake --cmake=\path\to\bin\cmake --openssl=\path\to\openssl\bin
