install:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: python --version
  - cmd: python setup.py install --qmake=\path\to\bin\qmake --cmake=\path\to\bin\cmake --openssl=\path\to\openssl\bin

build_script:
  - cmd: >-
      cmake --version
      dir
      cd C:\Qt
      curl -sLO https://download.qt.io/archive/qt/5.5/5.5.0/qt-opensource-windows-x86-msvc2010-5.5.0.exe
      7z x qt-opensource-windows-x86-msvc2010-5.5.0.exe
      cd C:\projects\pyside2-setup
      dir C:\Qt\5.5
      dir C:\Qt\5.5\msvc2013
      dir C:\Qt\5.5\Src
      dir C:\OpenSSL-Win32
      set QTDIR=C:\Qt\5.5\Src
      set PATH=%PATH%;%QTDIR%\bin
      qmake --version
      python setup.py install --openssl=C:\OpenSSL-Win32
